<?php

/**
 * Models_Solaria_JobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Models_Solaria_JobTable extends Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object Models_Solaria_JobTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Models_Solaria_Job');
    }
}
