<?php

/**
 * Models_Solaria_TaxRateProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Models_Solaria_TaxRateProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Models_Solaria_TaxRateProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Models_Solaria_TaxRateProduct');
    }
}