<?php

/**
 * Models_Main_ReporterInvoiceMasterDepartmentsToStaffTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Models_Main_ReporterInvoiceMasterDepartmentsToStaffTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Models_Main_ReporterInvoiceMasterDepartmentsToStaffTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Models_Main_ReporterInvoiceMasterDepartmentsToStaff');
    }
}