<?php

/**
 * Models_Main_TicketingLookupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Models_Main_TicketingLookupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Models_Main_TicketingLookupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Models_Main_TicketingLookup');
    }
}