<?php

/**
 * Models_Main_UserlistUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Models_Main_UserlistUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Models_Main_UserlistUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Models_Main_UserlistUsers');
    }
}