<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Models_Main_AffiliateCoverage', 'main');

/**
 * Models_Main_Base_AffiliateCoverage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $coverageID
 * @property integer $affiliateID
 * @property integer $cityID
 * @property integer $stateID
 * @property string $notes
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Main_Base_AffiliateCoverage extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('affiliate_coverage');
        $this->hasColumn('coverageID', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('affiliateID', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('cityID', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('stateID', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('notes', 'string', 350, array(
             'type' => 'string',
             'length' => 350,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}