<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Models_Main_Extensions', 'main');

/**
 * Models_Main_Base_Extensions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID_number
 * @property string $extension
 * @property string $description
 * @property string $branch
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Main_Base_Extensions extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('extensions');
        $this->hasColumn('ID_number', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('extension', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'default' => 'none',
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('description', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'default' => 'none',
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('branch', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'default' => 'none',
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}