<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Models_Main_RequestType', 'main');

/**
 * Models_Main_Base_RequestType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $requesttypeid
 * @property string $description
 * @property string $sortorder
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Main_Base_RequestType extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('request_type');
        $this->hasColumn('requesttypeid', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('description', 'string', 95, array(
             'type' => 'string',
             'length' => 95,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('sortorder', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}