<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Models_Main_Skills', 'main');

/**
 * Models_Main_Base_Skills
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $skill_id
 * @property string $skill_name
 * @property string $skill_category
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Main_Base_Skills extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('skills');
        $this->hasColumn('skill_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('skill_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('skill_category', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}