<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Models_Main_Trackingactions', 'main');

/**
 * Models_Main_Base_Trackingactions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ActionID
 * @property string $Code
 * @property string $Description
 * @property integer $Active
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Main_Base_Trackingactions extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('trackingactions');
        $this->hasColumn('ActionID', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('Code', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('Description', 'string', 95, array(
             'type' => 'string',
             'length' => 95,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('Active', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}