<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Models_Main_WpSticky', 'main');

/**
 * Models_Main_Base_WpSticky
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sticky_post_id
 * @property integer $sticky_status
 * @property integer $sticky_expire
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Main_Base_WpSticky extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('wp_sticky');
        $this->hasColumn('sticky_post_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('sticky_status', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('sticky_expire', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}