<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Models_Intranet_DeponentFile', 'intranet');

/**
 * Models_Intranet_Base_DeponentFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $file_path
 * @property integer $job_id
 * @property integer $job_number
 * @property integer $solaria_company_id
 * @property integer $transcript_type_id
 * @property boolean $confidential
 * @property integer $deponent_id
 * @property Models_Intranet_DeponentFileTranscriptType $DeponentFileTranscriptType
 * @property Models_Intranet_DeponentFileTranscriptType $DeponentFileTranscriptType_2
 * @property Doctrine_Collection $SummaryQueueDeponent
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Intranet_Base_DeponentFile extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('deponent_file');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('file_path', 'string', 300, array(
             'type' => 'string',
             'length' => '300',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('job_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('job_number', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('solaria_company_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('transcript_type_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('confidential', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('deponent_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Models_Intranet_DeponentFileTranscriptType as DeponentFileTranscriptType', array(
             'local' => 'transcript_type_id',
             'foreign' => 'id'));

        $this->hasOne('Models_Intranet_DeponentFileTranscriptType as DeponentFileTranscriptType_2', array(
             'local' => 'transcript_type_id',
             'foreign' => 'id'));

        $this->hasMany('Models_Intranet_SummaryQueueDeponent as SummaryQueueDeponent', array(
             'local' => 'id',
             'foreign' => 'deponent_file_id'));
    }
}