<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Models_Intranet_EmailListToEmail', 'intranet');

/**
 * Models_Intranet_Base_EmailListToEmail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $email_id
 * @property integer $email_list_id
 * @property Models_Intranet_Email $Email
 * @property Models_Intranet_EmailList $EmailList
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Intranet_Base_EmailListToEmail extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('email_list_to_email');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => true,
             ));
        $this->hasColumn('email_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('email_list_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Models_Intranet_Email as Email', array(
             'local' => 'email_id',
             'foreign' => 'id'));

        $this->hasOne('Models_Intranet_EmailList as EmailList', array(
             'local' => 'email_list_id',
             'foreign' => 'id'));
    }
}