<?php
/**
 * Models_Intranet_NpcPaymentInvoice
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Models_Intranet_NpcPaymentInvoice extends Models_Intranet_Base_NpcPaymentInvoice
{

}
