<?php

/**
 * Models_Intranet_RepositoryFileStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Models_Intranet_RepositoryFileStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Models_Intranet_RepositoryFileStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Models_Intranet_RepositoryFileStatus');
    }
}