<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html dir="ltr" xmlns="http://www.w3.org/1999/xhtml">

<head>
	<title>Court Reporters Portal, Job Worksheet</title>
	<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
	<link href="public/css/style_default.css" rel="stylesheet" type="text/css" media="screen"/>
	<link href="public/css/reporter_worksheet.css" rel="stylesheet" type="text/css" media="screen"/>
	<link rel="stylesheet" href="public/js/library/ext-4.0.7/resources/css/ext-all.css" 
		  type="text/css" media="screen" 
	/>
	<script type="text/javascript" src="public/js/library/ext-4.0.7/ext-all-debug.js"></script>
	<script type="text/javascript" src="public/js/crp_worksheet_framework.js"></script>
<?php 
echo $this->headScript(); 
?>

</head>
<body>
</body>
</html>
