<?php

/**
 * Models_Solaria_Base_AttorneyProductPrice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $AttorneyProductPriceID
 * @property integer $AttorneyID
 * @property integer $ProductID
 * @property decimal $UnitPrice
 * @property integer $JobTypeID
 * @property integer $DeliveryTypeID
 * @property Models_Solaria_Attorney $Attorney
 * @property Models_Solaria_Product $Product
 * @property Models_Solaria_JobType $JobType
 * @property Models_Solaria_DeliveryType $DeliveryType
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Solaria_Base_AttorneyProductPrice extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('AttorneyProductPrice');
        $this->hasColumn('AttorneyProductPriceID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('AttorneyID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('ProductID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('UnitPrice', 'decimal', 21, array(
             'type' => 'decimal',
             'length' => '21',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('JobTypeID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('DeliveryTypeID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Models_Solaria_Attorney as Attorney', array(
             'local' => 'AttorneyID',
             'foreign' => 'AttorneyID'));

        $this->hasOne('Models_Solaria_Product as Product', array(
             'local' => 'ProductID',
             'foreign' => 'ProductID'));

        $this->hasOne('Models_Solaria_JobType as JobType', array(
             'local' => 'JobTypeID',
             'foreign' => 'JobTypeID'));

        $this->hasOne('Models_Solaria_DeliveryType as DeliveryType', array(
             'local' => 'DeliveryTypeID',
             'foreign' => 'DeliveryTypeID'));
    }
}
