<?php

/**
 * Models_Solaria_Base_AttorneyPrefs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $AttorneyPrefsID
 * @property integer $AttorneyID
 * @property boolean $OverrideProductPrices
 * @property boolean $OverrideDefaults
 * @property boolean $IsInvoiced
 * @property boolean $IsChargedInterest
 * @property integer $InvoiceTypeID
 * @property boolean $IsSentMailings
 * @property integer $TemplateID
 * @property integer $InvoiceTermID
 * @property integer $PriceTemplateID
 * @property Models_Solaria_Attorney $Attorney
 * @property Models_Solaria_InvoiceType $InvoiceType
 * @property Models_Solaria_Template $Template
 * @property Models_Solaria_InvoiceTerm $InvoiceTerm
 * @property Models_Solaria_PriceTemplate $PriceTemplate
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Solaria_Base_AttorneyPrefs extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('AttorneyPrefs');
        $this->hasColumn('AttorneyPrefsID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('AttorneyID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('OverrideProductPrices', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('OverrideDefaults', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('IsInvoiced', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('IsChargedInterest', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('InvoiceTypeID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('IsSentMailings', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('TemplateID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('InvoiceTermID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('PriceTemplateID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Models_Solaria_Attorney as Attorney', array(
             'local' => 'AttorneyID',
             'foreign' => 'AttorneyID'));

        $this->hasOne('Models_Solaria_InvoiceType as InvoiceType', array(
             'local' => 'InvoiceTypeID',
             'foreign' => 'InvoiceTypeID'));

        $this->hasOne('Models_Solaria_Template as Template', array(
             'local' => 'TemplateID',
             'foreign' => 'TemplateID'));

        $this->hasOne('Models_Solaria_InvoiceTerm as InvoiceTerm', array(
             'local' => 'InvoiceTermID',
             'foreign' => 'InvoiceTermID'));

        $this->hasOne('Models_Solaria_PriceTemplate as PriceTemplate', array(
             'local' => 'PriceTemplateID',
             'foreign' => 'PriceTemplateID'));
    }
}
