<?php

/**
 * Models_Solaria_Base_CommissionTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $CommissionTemplateID
 * @property string $Description
 * @property integer $CommissionsCalcType
 * @property decimal $InvoiceChargesPerc
 * @property Doctrine_Collection $CommissionProductRate
 * @property Doctrine_Collection $StaffClientSales
 * @property Doctrine_Collection $StaffInvoice
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Solaria_Base_CommissionTemplate extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('CommissionTemplate');
        $this->hasColumn('CommissionTemplateID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('Description', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('CommissionsCalcType', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('InvoiceChargesPerc', 'decimal', 21, array(
             'type' => 'decimal',
             'length' => '21',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Models_Solaria_CommissionProductRate as CommissionProductRate', array(
             'local' => 'CommissionTemplateID',
             'foreign' => 'CommissionTemplateID'));

        $this->hasMany('Models_Solaria_StaffClientSales as StaffClientSales', array(
             'local' => 'CommissionTemplateID',
             'foreign' => 'CommissionTemplateID'));

        $this->hasMany('Models_Solaria_StaffInvoice as StaffInvoice', array(
             'local' => 'CommissionTemplateID',
             'foreign' => 'CommissionTemplateID'));
    }
}
