<?php

/**
 * Models_Solaria_Base_CompanyAccount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $CompanyAccountID
 * @property integer $CompanyID
 * @property string $AcctsReceivableAcct
 * @property string $AcctsPayableAcct
 * @property string $CheckingAcct
 * @property string $CreditCardAcct
 * @property string $SalesIncomeAcct
 * @property string $StaffLaborAcct
 * @property string $StaffExpenseAcct
 * @property string $StaffCommissionAcct
 * @property string $SalesTaxPayableAcct
 * @property string $UndepositedAcct
 * @property Models_Solaria_Company $Company
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Solaria_Base_CompanyAccount extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('CompanyAccount');
        $this->hasColumn('CompanyAccountID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('CompanyID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('AcctsReceivableAcct', 'string', 35, array(
             'type' => 'string',
             'length' => '35',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('AcctsPayableAcct', 'string', 35, array(
             'type' => 'string',
             'length' => '35',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('CheckingAcct', 'string', 35, array(
             'type' => 'string',
             'length' => '35',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('CreditCardAcct', 'string', 35, array(
             'type' => 'string',
             'length' => '35',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('SalesIncomeAcct', 'string', 35, array(
             'type' => 'string',
             'length' => '35',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('StaffLaborAcct', 'string', 35, array(
             'type' => 'string',
             'length' => '35',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('StaffExpenseAcct', 'string', 35, array(
             'type' => 'string',
             'length' => '35',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('StaffCommissionAcct', 'string', 35, array(
             'type' => 'string',
             'length' => '35',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('SalesTaxPayableAcct', 'string', 35, array(
             'type' => 'string',
             'length' => '35',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('UndepositedAcct', 'string', 35, array(
             'type' => 'string',
             'length' => '35',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Models_Solaria_Company as Company', array(
             'local' => 'CompanyID',
             'foreign' => 'CompanyID'));
    }
}
