<?php

/**
 * Models_Solaria_Base_CustomLookupValue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $CustomLookupValueID
 * @property integer $CustomFieldID
 * @property string $Code
 * @property string $Description
 * @property boolean $IsDefault
 * @property boolean $IsActive
 * @property Models_Solaria_CustomField $CustomField
 * @property Doctrine_Collection $CaseECSClient
 * @property Doctrine_Collection $EntityCustomFieldValue
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Solaria_Base_CustomLookupValue extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('CustomLookupValue');
        $this->hasColumn('CustomLookupValueID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('CustomFieldID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('Code', 'string', 8, array(
             'type' => 'string',
             'length' => '8',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('Description', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('IsDefault', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('IsActive', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Models_Solaria_CustomField as CustomField', array(
             'local' => 'CustomFieldID',
             'foreign' => 'CustomFieldID'));

        $this->hasMany('Models_Solaria_CaseECSClient as CaseECSClient', array(
             'local' => 'CustomLookupValueID',
             'foreign' => 'CustomLookupValueID1'));

        $this->hasMany('Models_Solaria_EntityCustomFieldValue as EntityCustomFieldValue', array(
             'local' => 'CustomLookupValueID',
             'foreign' => 'CustomLookupValueID'));
    }
}
