<?php

/**
 * Models_Solaria_Base_EditLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $EditLogID
 * @property integer $UserID
 * @property string $EditType
 * @property timestamp $DateChanged
 * @property string $TableName
 * @property string $KeyName
 * @property integer $KeyValue
 * @property string $FieldName
 * @property string $BeforeValue
 * @property string $AfterValue
 * @property string $Application
 * @property string $GUID
 * @property Models_Solaria_SystemUser $SystemUser
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Solaria_Base_EditLog extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('EditLog');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Models_Solaria_SystemUser as SystemUser', array(
             'local' => 'UserID',
             'foreign' => 'UserID'));
    }
}
