<?php

/**
 * Models_Solaria_Base_FileType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $FileTypeID
 * @property string $Description
 * @property integer $ApplicationTypeID
 * @property boolean $IsActive
 * @property boolean $IsSystemDefined
 * @property Models_Solaria_ApplicationType $ApplicationType
 * @property Doctrine_Collection $FileAttachment
 * @property Doctrine_Collection $JobFile
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Solaria_Base_FileType extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('FileType');
        $this->hasColumn('FileTypeID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('Description', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('ApplicationTypeID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('IsActive', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('IsSystemDefined', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Models_Solaria_ApplicationType as ApplicationType', array(
             'local' => 'ApplicationTypeID',
             'foreign' => 'ApplicationTypeID'));

        $this->hasMany('Models_Solaria_FileAttachment as FileAttachment', array(
             'local' => 'FileTypeID',
             'foreign' => 'FileTypeID'));

        $this->hasMany('Models_Solaria_JobFile as JobFile', array(
             'local' => 'FileTypeID',
             'foreign' => 'FileTypeID'));
    }
}
