<?php

/**
 * Models_Solaria_Base_InvoiceTerm
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $InvoiceTermID
 * @property string $Description
 * @property boolean $IsActive
 * @property boolean $IsSystemDefined
 * @property integer $DaysUntilDue
 * @property Doctrine_Collection $AttorneyPrefs
 * @property Doctrine_Collection $ClientPrefs
 * @property Doctrine_Collection $Invoice
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Solaria_Base_InvoiceTerm extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('InvoiceTerm');
        $this->hasColumn('InvoiceTermID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('Description', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('IsActive', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('IsSystemDefined', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('DaysUntilDue', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Models_Solaria_AttorneyPrefs as AttorneyPrefs', array(
             'local' => 'InvoiceTermID',
             'foreign' => 'InvoiceTermID'));

        $this->hasMany('Models_Solaria_ClientPrefs as ClientPrefs', array(
             'local' => 'InvoiceTermID',
             'foreign' => 'InvoiceTermID'));

        $this->hasMany('Models_Solaria_Invoice as Invoice', array(
             'local' => 'InvoiceTermID',
             'foreign' => 'InvoiceTermID'));
    }
}
