<?php

/**
 * Models_Solaria_Base_InvoiceChargeType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $InvoiceChargeTypeID
 * @property string $Description
 * @property string $ChargeTypeCode
 * @property boolean $IsActive
 * @property boolean $IsSystemDefined
 * @property string $Code
 * @property string $GLCode
 * @property boolean $IsLimitedUsers
 * @property string $GLCodeLOB
 * @property boolean $IsECSRedirect
 * @property integer $CentralID
 * @property Doctrine_Collection $InvoiceChargeRate
 * @property Doctrine_Collection $InvoiceItem
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Solaria_Base_InvoiceChargeType extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('InvoiceChargeType');
        $this->hasColumn('InvoiceChargeTypeID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('Description', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('ChargeTypeCode', 'string', 4, array(
             'type' => 'string',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('IsActive', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('IsSystemDefined', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('Code', 'string', 6, array(
             'type' => 'string',
             'length' => '6',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('GLCode', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('IsLimitedUsers', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('GLCodeLOB', 'string', 5, array(
             'type' => 'string',
             'length' => '5',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('IsECSRedirect', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('CentralID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Models_Solaria_InvoiceChargeRate as InvoiceChargeRate', array(
             'local' => 'InvoiceChargeTypeID',
             'foreign' => 'InvoiceChargeTypeID'));

        $this->hasMany('Models_Solaria_InvoiceItem as InvoiceItem', array(
             'local' => 'InvoiceChargeTypeID',
             'foreign' => 'InvoiceChargeTypeID'));
    }
}
