<?php

/**
 * Models_Solaria_Base_InvoiceItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $InvoiceItemID
 * @property integer $InvoiceChargeTypeID
 * @property string $ChargeTypeCode
 * @property string $PrintedDescription
 * @property string $UnitDescription
 * @property float $Qty
 * @property decimal $UnitPrice
 * @property decimal $AmountDue
 * @property integer $InvoiceID
 * @property decimal $AmountPaid
 * @property decimal $Balance
 * @property timestamp $PaidOn
 * @property timestamp $ItemDate
 * @property string $GLCodeLocation
 * @property float $DefaultRate
 * @property Models_Solaria_InvoiceChargeType $InvoiceChargeType
 * @property Models_Solaria_Invoice $Invoice
 * @property Models_Solaria_Invoice $Invoice_3
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Solaria_Base_InvoiceItem extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('InvoiceItem');
        $this->hasColumn('InvoiceItemID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('InvoiceChargeTypeID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('ChargeTypeCode', 'string', 4, array(
             'type' => 'string',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('PrintedDescription', 'string', 60, array(
             'type' => 'string',
             'length' => '60',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('UnitDescription', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('Qty', 'float', 18, array(
             'type' => 'float',
             'length' => '18',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('UnitPrice', 'decimal', 21, array(
             'type' => 'decimal',
             'length' => '21',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('AmountDue', 'decimal', 21, array(
             'type' => 'decimal',
             'length' => '21',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('InvoiceID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('AmountPaid', 'decimal', 21, array(
             'type' => 'decimal',
             'length' => '21',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('Balance', 'decimal', 21, array(
             'type' => 'decimal',
             'length' => '21',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('PaidOn', 'timestamp', 16, array(
             'type' => 'timestamp',
             'length' => '16',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('ItemDate', 'timestamp', 16, array(
             'type' => 'timestamp',
             'length' => '16',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('GLCodeLocation', 'string', 5, array(
             'type' => 'string',
             'length' => '5',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('DefaultRate', 'float', 18, array(
             'type' => 'float',
             'length' => '18',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Models_Solaria_InvoiceChargeType as InvoiceChargeType', array(
             'local' => 'InvoiceChargeTypeID',
             'foreign' => 'InvoiceChargeTypeID'));

        $this->hasOne('Models_Solaria_Invoice as Invoice', array(
             'local' => 'InvoiceID',
             'foreign' => 'InvoiceID'));

        $this->hasOne('Models_Solaria_Invoice as Invoice_3', array(
             'local' => 'InvoiceID',
             'foreign' => 'InvoiceID'));
    }
}
