<?php

/**
 * Models_Solaria_Base_JobAttorneyDeponent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $JobID
 * @property integer $AttorneyID
 * @property integer $DeponentID
 * @property Models_Solaria_Job $Job
 * @property Models_Solaria_Attorney $Attorney
 * @property Models_Solaria_Deponent $Deponent
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Solaria_Base_JobAttorneyDeponent extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('JobAttorneyDeponent');
        $this->hasColumn('JobID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('AttorneyID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('DeponentID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Models_Solaria_Job as Job', array(
             'local' => 'JobID',
             'foreign' => 'JobID'));

        $this->hasOne('Models_Solaria_Attorney as Attorney', array(
             'local' => 'AttorneyID',
             'foreign' => 'AttorneyID'));

        $this->hasOne('Models_Solaria_Deponent as Deponent', array(
             'local' => 'DeponentID',
             'foreign' => 'DeponentID'));
    }
}
