<?php

/**
 * Models_Solaria_Base_OrderDeponentDeliverable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $OrderDeponentDeliverableID
 * @property integer $OrderID
 * @property integer $DeponentID
 * @property integer $DeliverableID
 * @property boolean $IsOriginal
 * @property integer $DeliveryMediumID
 * @property Models_Solaria_Orders $Orders
 * @property Models_Solaria_Deponent $Deponent
 * @property Models_Solaria_Deliverable $Deliverable
 * @property Models_Solaria_DeliveryMedium $DeliveryMedium
 * @property Doctrine_Collection $OrderDeponentDeliverableOption
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Solaria_Base_OrderDeponentDeliverable extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('OrderDeponentDeliverable');
        $this->hasColumn('OrderDeponentDeliverableID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('OrderID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('DeponentID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('DeliverableID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('IsOriginal', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'default' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('DeliveryMediumID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Models_Solaria_Orders as Orders', array(
             'local' => 'OrderID',
             'foreign' => 'OrderID'));

        $this->hasOne('Models_Solaria_Deponent as Deponent', array(
             'local' => 'DeponentID',
             'foreign' => 'DeponentID'));

        $this->hasOne('Models_Solaria_Deliverable as Deliverable', array(
             'local' => 'DeliverableID',
             'foreign' => 'DeliverableID'));

        $this->hasOne('Models_Solaria_DeliveryMedium as DeliveryMedium', array(
             'local' => 'DeliveryMediumID',
             'foreign' => 'DeliveryMediumID'));

        $this->hasMany('Models_Solaria_OrderDeponentDeliverableOption as OrderDeponentDeliverableOption', array(
             'local' => 'OrderDeponentDeliverableID',
             'foreign' => 'OrderDeponentDeliverableID'));
    }
}
