<?php

/**
 * Models_Solaria_Base_OrderProofOfOrdering
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $OrderProofOfOrderingID
 * @property integer $OrderID
 * @property integer $ProofOfOrderingID
 * @property boolean $Value
 * @property Models_Solaria_Orders $Orders
 * @property Models_Solaria_ProofOfOrdering $ProofOfOrdering
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Solaria_Base_OrderProofOfOrdering extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('OrderProofOfOrdering');
        $this->hasColumn('OrderProofOfOrderingID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('OrderID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('ProofOfOrderingID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('Value', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Models_Solaria_Orders as Orders', array(
             'local' => 'OrderID',
             'foreign' => 'OrderID'));

        $this->hasOne('Models_Solaria_ProofOfOrdering as ProofOfOrdering', array(
             'local' => 'ProofOfOrderingID',
             'foreign' => 'ProofOfOrderingID'));
    }
}