<?php

/**
 * Models_Solaria_Base_Orders
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $OrderID
 * @property integer $CompanyID
 * @property integer $JobID
 * @property integer $ClientID
 * @property integer $AttorneyID
 * @property integer $ContactID
 * @property timestamp $OrderedDate
 * @property timestamp $DeliveryDueOn
 * @property timestamp $CompletedOn
 * @property integer $ShippingMethodID
 * @property timestamp $ShippedOn
 * @property integer $BillingAddressID
 * @property string $ShippedToName
 * @property integer $ShippingAddressID
 * @property integer $OrderStatus
 * @property timestamp $EditedOn
 * @property integer $UserID
 * @property integer $BillingClientID
 * @property integer $BillingAttorneyID
 * @property boolean $IsShipSameAsBill
 * @property integer $DeliveryTypeID
 * @property boolean $IsVoided
 * @property boolean $RepositoryAccess
 * @property boolean $IsRecurring
 * @property integer $RecurType
 * @property integer $RecurNumMonths
 * @property integer $OrderTemplateID
 * @property integer $ShipToClientID
 * @property integer $ShipToAttorneyID
 * @property integer $ReportingTemplateID
 * @property integer $OrderTypeID
 * @property Models_Solaria_Company $Company
 * @property Models_Solaria_Job $Job
 * @property Models_Solaria_Client $Client
 * @property Models_Solaria_Attorney $Attorney
 * @property Models_Solaria_Contact $Contact
 * @property Models_Solaria_ShippingMethod $ShippingMethod
 * @property Models_Solaria_SystemUser $SystemUser
 * @property Models_Solaria_DeliveryType $DeliveryType
 * @property Models_Solaria_Template $Template
 * @property Models_Solaria_Client $Client_10
 * @property Models_Solaria_Attorney $Attorney_11
 * @property Models_Solaria_OrderType $OrderType
 * @property Doctrine_Collection $Invoice
 * @property Doctrine_Collection $OrderItem
 * @property Doctrine_Collection $StaffInvoiceItem
 * @property Doctrine_Collection $StaffInvoiceOrder
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Solaria_Base_Orders extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('Orders');
        $this->hasColumn('OrderID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('CompanyID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('JobID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('ClientID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('AttorneyID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('ContactID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('OrderedDate', 'timestamp', 16, array(
             'type' => 'timestamp',
             'length' => '16',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('DeliveryDueOn', 'timestamp', 16, array(
             'type' => 'timestamp',
             'length' => '16',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('CompletedOn', 'timestamp', 16, array(
             'type' => 'timestamp',
             'length' => '16',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('ShippingMethodID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('ShippedOn', 'timestamp', 16, array(
             'type' => 'timestamp',
             'length' => '16',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('BillingAddressID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('ShippedToName', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('ShippingAddressID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('OrderStatus', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('EditedOn', 'timestamp', 16, array(
             'type' => 'timestamp',
             'length' => '16',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('UserID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('BillingClientID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('BillingAttorneyID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('IsShipSameAsBill', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('DeliveryTypeID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('IsVoided', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('RepositoryAccess', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('IsRecurring', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'default' => 0,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('RecurType', 'integer', 2, array(
             'type' => 'integer',
             'length' => '2',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'default' => 0,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('RecurNumMonths', 'integer', 2, array(
             'type' => 'integer',
             'length' => '2',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'default' => 0,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('OrderTemplateID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('ShipToClientID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('ShipToAttorneyID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('ReportingTemplateID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('OrderTypeID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Models_Solaria_Company as Company', array(
             'local' => 'CompanyID',
             'foreign' => 'CompanyID'));

        $this->hasOne('Models_Solaria_Job as Job', array(
             'local' => 'JobID',
             'foreign' => 'JobID'));

        $this->hasOne('Models_Solaria_Client as Client', array(
             'local' => 'ClientID',
             'foreign' => 'ClientID'));

        $this->hasOne('Models_Solaria_Attorney as Attorney', array(
             'local' => 'AttorneyID',
             'foreign' => 'AttorneyID'));

        $this->hasOne('Models_Solaria_Contact as Contact', array(
             'local' => 'ContactID',
             'foreign' => 'ContactID'));

        $this->hasOne('Models_Solaria_ShippingMethod as ShippingMethod', array(
             'local' => 'ShippingMethodID',
             'foreign' => 'ShippingMethodID'));

        $this->hasOne('Models_Solaria_SystemUser as SystemUser', array(
             'local' => 'UserID',
             'foreign' => 'UserID'));

        $this->hasOne('Models_Solaria_DeliveryType as DeliveryType', array(
             'local' => 'DeliveryTypeID',
             'foreign' => 'DeliveryTypeID'));

        $this->hasOne('Models_Solaria_Template as Template', array(
             'local' => 'OrderTemplateID',
             'foreign' => 'TemplateID'));

        $this->hasOne('Models_Solaria_Client as ShippingClient', array(
             'local' => 'ShipToClientID',
             'foreign' => 'ClientID'));

        $this->hasOne('Models_Solaria_Client as BillingClient', array(
             'local' => 'BillingClientID',
             'foreign' => 'ClientID'));

        $this->hasOne('Models_Solaria_Attorney as ShippingAttorney', array(
             'local' => 'ShipToAttorneyID',
             'foreign' => 'AttorneyID'));

        $this->hasOne('Models_Solaria_Attorney as BillingAttorney', array(
             'local' => 'BillingAttorneyID',
             'foreign' => 'AttorneyID'));

        $this->hasOne('Models_Solaria_OrderType as OrderType', array(
             'local' => 'OrderTypeID',
             'foreign' => 'OrderTypeID'));

        $this->hasMany('Models_Solaria_Invoice as Invoice', array(
             'local' => 'OrderID',
             'foreign' => 'OrderID'));

        $this->hasMany('Models_Solaria_OrderItem as OrderItem', array(
             'local' => 'OrderID',
             'foreign' => 'OrderID'));

        $this->hasMany('Models_Solaria_StaffInvoiceItem as StaffInvoiceItem', array(
             'local' => 'OrderID',
             'foreign' => 'ClientOrderID'));

        $this->hasMany('Models_Solaria_StaffInvoiceOrder as StaffInvoiceOrder', array(
             'local' => 'OrderID',
             'foreign' => 'OrderID'));
    }
}
