<?php

/**
 * Models_Solaria_Base_PriceTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $PriceTemplateID
 * @property string $Description
 * @property boolean $IsActive
 * @property boolean $IsMasterTemplate
 * @property timestamp $EditedOn
 * @property integer $UserID
 * @property integer $CompanyID
 * @property integer $CSDTypeID
 * @property Models_Solaria_SystemUser $SystemUser
 * @property Models_Solaria_Company $Company
 * @property Models_Solaria_CSDType $CSDType
 * @property Doctrine_Collection $AttorneyPrefs
 * @property Doctrine_Collection $Cases
 * @property Doctrine_Collection $ClientPrefs
 * @property Doctrine_Collection $Invoice
 * @property Doctrine_Collection $ProductPriceTemplate
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Solaria_Base_PriceTemplate extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('PriceTemplate');
        $this->hasColumn('PriceTemplateID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('Description', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('IsActive', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(1)',
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('IsMasterTemplate', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => '1',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'default' => '(0)',
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('EditedOn', 'timestamp', 16, array(
             'type' => 'timestamp',
             'length' => '16',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('UserID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('CompanyID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('CSDTypeID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Models_Solaria_SystemUser as SystemUser', array(
             'local' => 'UserID',
             'foreign' => 'UserID'));

        $this->hasOne('Models_Solaria_Company as Company', array(
             'local' => 'CompanyID',
             'foreign' => 'CompanyID'));

        $this->hasOne('Models_Solaria_CSDType as CSDType', array(
             'local' => 'CSDTypeID',
             'foreign' => 'CSDTypeID'));

        $this->hasMany('Models_Solaria_AttorneyPrefs as AttorneyPrefs', array(
             'local' => 'PriceTemplateID',
             'foreign' => 'PriceTemplateID'));

        $this->hasMany('Models_Solaria_Cases as Cases', array(
             'local' => 'PriceTemplateID',
             'foreign' => 'PriceTemplateID'));

        $this->hasMany('Models_Solaria_ClientPrefs as ClientPrefs', array(
             'local' => 'PriceTemplateID',
             'foreign' => 'PriceTemplateID'));

        $this->hasMany('Models_Solaria_Invoice as Invoice', array(
             'local' => 'PriceTemplateID',
             'foreign' => 'PriceTemplateID'));

        $this->hasMany('Models_Solaria_ProductPriceTemplate as ProductPriceTemplate', array(
             'local' => 'PriceTemplateID',
             'foreign' => 'PriceTemplateID'));
    }
}
