<?php

/**
 * Models_Solaria_Base_ProductTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ProductID
 * @property integer $TemplateID
 * @property Models_Solaria_Product $Product
 * @property Models_Solaria_Template $Template
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Solaria_Base_ProductTemplate extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('ProductTemplate');
        $this->hasColumn('ProductID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('TemplateID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Models_Solaria_Product as Product', array(
             'local' => 'ProductID',
             'foreign' => 'ProductID'));

        $this->hasOne('Models_Solaria_Template as Template', array(
             'local' => 'TemplateID',
             'foreign' => 'TemplateID'));
    }
}
