<?php

/**
 * Models_Solaria_Base_ReadAndSign
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ReadAndSignID
 * @property string $WitnessAttorneyName
 * @property integer $DaysTimeLimit
 * @property integer $SignatureProtocolID
 * @property string $WitnessSignature
 * @property Models_Solaria_SignatureProtocol $SignatureProtocol
 * @property Doctrine_Collection $JobDeponent
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Solaria_Base_ReadAndSign extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('ReadAndSign');
        $this->hasColumn('ReadAndSignID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('WitnessAttorneyName', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('DaysTimeLimit', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('SignatureProtocolID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('WitnessSignature', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Models_Solaria_SignatureProtocol as SignatureProtocol', array(
             'local' => 'SignatureProtocolID',
             'foreign' => 'SignatureProtocolID'));

        $this->hasMany('Models_Solaria_JobDeponent as JobDeponent', array(
             'local' => 'ReadAndSignID',
             'foreign' => 'ReadAndSignID'));
    }
}
