<?php

/**
 * Models_Solaria_Base_StaffExpense
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $StaffExpenseID
 * @property integer $StaffID
 * @property integer $ExpenseTypeID
 * @property integer $StaffInvoiceID
 * @property string $Description
 * @property float $Qty
 * @property decimal $UnitPrice
 * @property decimal $AmountDue
 * @property decimal $AmountPaid
 * @property decimal $Balance
 * @property timestamp $PaidOn
 * @property float $DefaultRate
 * @property Models_Solaria_Staff $Staff
 * @property Models_Solaria_ExpenseType $ExpenseType
 * @property Models_Solaria_StaffInvoice $StaffInvoice
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Solaria_Base_StaffExpense extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('StaffExpense');
        $this->hasColumn('StaffExpenseID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('StaffID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('ExpenseTypeID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('StaffInvoiceID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('Description', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('Qty', 'float', 18, array(
             'type' => 'float',
             'length' => '18',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('UnitPrice', 'decimal', 21, array(
             'type' => 'decimal',
             'length' => '21',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('AmountDue', 'decimal', 21, array(
             'type' => 'decimal',
             'length' => '21',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('AmountPaid', 'decimal', 21, array(
             'type' => 'decimal',
             'length' => '21',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('Balance', 'decimal', 21, array(
             'type' => 'decimal',
             'length' => '21',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('PaidOn', 'timestamp', 16, array(
             'type' => 'timestamp',
             'length' => '16',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('DefaultRate', 'float', 18, array(
             'type' => 'float',
             'length' => '18',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'default' => '((0))',
             'primary' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Models_Solaria_Staff as Staff', array(
             'local' => 'StaffID',
             'foreign' => 'StaffID'));

        $this->hasOne('Models_Solaria_ExpenseType as ExpenseType', array(
             'local' => 'ExpenseTypeID',
             'foreign' => 'ExpenseTypeID'));

        $this->hasOne('Models_Solaria_StaffInvoice as StaffInvoice', array(
             'local' => 'StaffInvoiceID',
             'foreign' => 'StaffInvoiceID'));
    }
}
