<?php

/**
 * Models_Solaria_Base_StaffGuarantee
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $StaffGuaranteeID
 * @property integer $StaffID
 * @property integer $GuaranteeTypeID
 * @property string $ProductTypeCode
 * @property Models_Solaria_Staff $Staff
 * @property Models_Solaria_GuaranteeType $GuaranteeType
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Solaria_Base_StaffGuarantee extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('StaffGuarantee');
        $this->hasColumn('StaffGuaranteeID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('StaffID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('GuaranteeTypeID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('ProductTypeCode', 'string', 4, array(
             'type' => 'string',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Models_Solaria_Staff as Staff', array(
             'local' => 'StaffID',
             'foreign' => 'StaffID'));

        $this->hasOne('Models_Solaria_GuaranteeType as GuaranteeType', array(
             'local' => 'GuaranteeTypeID',
             'foreign' => 'GuaranteeTypeID'));
    }
}
