<?php

/**
 * Models_Solaria_Base_StaffService
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $StaffID
 * @property integer $ServiceID
 * @property Models_Solaria_Staff $Staff
 * @property Models_Solaria_Service $Service
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Solaria_Base_StaffService extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('StaffService');
        $this->hasColumn('StaffID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('ServiceID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Models_Solaria_Staff as Staff', array(
             'local' => 'StaffID',
             'foreign' => 'StaffID'));

        $this->hasOne('Models_Solaria_Service as Service', array(
             'local' => 'ServiceID',
             'foreign' => 'ServiceID'));
    }
}
