<?php

/**
 * Models_Solaria_Base_TransItemSplit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $TransItemSplitID
 * @property integer $TransactionItemID
 * @property string $ItemType
 * @property integer $ItemID
 * @property decimal $AmountPaid
 * @property Models_Solaria_TransactionItem $TransactionItem
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Models_Solaria_Base_TransItemSplit extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('TransItemSplit');
        $this->hasColumn('TransItemSplitID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('TransactionItemID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('ItemType', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('ItemID', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('AmountPaid', 'decimal', 21, array(
             'type' => 'decimal',
             'length' => '21',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Models_Solaria_TransactionItem as TransactionItem', array(
             'local' => 'TransactionItemID',
             'foreign' => 'TransactionItemID'));
    }
}
